"""create reports table

Revision ID: 3b97768f40b5
Revises: 68cbbc3bdb68
Create Date: 2026-04-29 12:35:27.139396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3b97768f40b5'
down_revision: Union[str, Sequence[str], None] = '68cbbc3bdb68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('pdf_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('signal_count', sa.Integer(), nullable=False),
    sa.Column('data_points', sa.Integer(), nullable=False),
    sa.Column('exec_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_week'), 'reports', ['week'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_week'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
