"""create signals table

Revision ID: 68cbbc3bdb68
Revises: edd6015c7323
Create Date: 2026-04-29 11:22:19.566575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '68cbbc3bdb68'
down_revision: Union[str, Sequence[str], None] = 'edd6015c7323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recommended_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recommended_owner', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('confidence', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('source_refs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_competitor_id'), 'signals', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_signals_created_at'), 'signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_signals_severity'), 'signals', ['severity'], unique=False)
    op.create_index(op.f('ix_signals_week'), 'signals', ['week'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_week'), table_name='signals')
    op.drop_index(op.f('ix_signals_severity'), table_name='signals')
    op.drop_index(op.f('ix_signals_created_at'), table_name='signals')
    op.drop_index(op.f('ix_signals_competitor_id'), table_name='signals')
    op.drop_table('signals')
    # ### end Alembic commands ###
