"""create company_events table

Revision ID: b8edb6a3cf05
Revises: b3043c8f68f0
Create Date: 2026-04-29 10:10:32.483045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b8edb6a3cf05'
down_revision: Union[str, Sequence[str], None] = 'b3043c8f68f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_events_competitor_id'), 'company_events', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_company_events_detected_at'), 'company_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_company_events_event_type'), 'company_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_company_events_source'), 'company_events', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_events_source'), table_name='company_events')
    op.drop_index(op.f('ix_company_events_event_type'), table_name='company_events')
    op.drop_index(op.f('ix_company_events_detected_at'), table_name='company_events')
    op.drop_index(op.f('ix_company_events_competitor_id'), table_name='company_events')
    op.drop_table('company_events')
    # ### end Alembic commands ###
