"""create competitors table

Revision ID: f4d42f6003c8
Revises: 
Create Date: 2026-04-28 12:40:36.437674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f4d42f6003c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('cvr', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('career_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('scraper_config', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_slug'), 'competitors', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitors_slug'), table_name='competitors')
    op.drop_table('competitors')
    # ### end Alembic commands ###
